apiVersion: v1
kind: Namespace
metadata:
  name: rabbitmq

---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-config
  namespace: rabbitmq
type: Opaque
stringData:
  rabbitmq.conf: |-
    listeners.tcp.default = 5672
    loopback_users.guest = false
  enabled_plugins: |-
    [rabbitmq_management].
#  definitions.json: |-
#    {
#      "users": [],
#      "vhosts": [
#        {
#          "name": "/"
#        }
#      ],
#      "permissions": []
#    }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-mnesia-pvc
  namespace: rabbitmq
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-data-pvc
  namespace: rabbitmq
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - name: amqp
      port: 5672
    - name: management
      port: 15672

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.9.8-management
          ports:
            - containerPort: 5672
              name: amqp
            - containerPort: 15672
              name: management
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
            - name: rabbitmq-config
              mountPath: /etc/rabbitmq
            - name: rabbitmq-mnesia
              mountPath: /var/lib/rabbitmq/mnesia
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim:
            claimName: rabbitmq-data-pvc
        - name: rabbitmq-config
          secret:
            secretName: rabbitmq-config
        - name: rabbitmq-mnesia
          persistentVolumeClaim:
            claimName: rabbitmq-mnesia-pvc