name: nameko-devex
channels:
- conda-forge
dependencies:
- openjdk=8.0                       #dev
- python=3.7
- pip==21
- pip:
    - nameko==2.14.1 #v3.0.0-rc9
    - importlib-metadata==6.5
    - fastapi==0.70.0
    - uvicorn==0.15.0
    - marshmallow==2.19.2
    - psycopg2-binary==2.9.6
    - sqlalchemy==2.0.18
    - nameko-sqlalchemy==1.5.0
    - alembic==1.11.1
    - pylint==2.5.2                 #dev
    - debugpy==1.0.0b9              #dev
    - bzt==1.15.3                   #dev
    - pytest==7.2.0                 #dev
    - coverage==4.5.3               #dev
    - flake8==3.7.7                 #dev
    - redis==3.2.1