apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: 198.201.0.0
  namespace: metallb-system
spec:
  addresses:
  - 198.201.0.200-198.201.0.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system
