"""init

Revision ID: 371449d8ec49
Revises: abb2e19ead13
Create Date: 2023-07-08 21:18:57.939402

"""

# revision identifiers, used by Alembic.
revision = '371449d8ec49'
down_revision = 'abb2e19ead13'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
