apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-autoscaler
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/AmazonEKSClusterAutoscalerRole
secrets:
  - name: cluster-autoscaler-token
---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-autoscaler-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: cluster-autoscaler
type: kubernetes.io/service-account-token
