"""init

Revision ID: abb2e19ead13
Revises: dd33cb03d01f
Create Date: 2023-07-08 21:05:02.893018

"""

# revision identifiers, used by Alembic.
revision = 'abb2e19ead13'
down_revision = 'dd33cb03d01f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
