"""init

Revision ID: f0fc62bea9f2
Revises: 371449d8ec49
Create Date: 2023-07-18 20:42:26.645712

"""

# revision identifiers, used by Alembic.
revision = 'f0fc62bea9f2'
down_revision = '371449d8ec49'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
